"""
Trains the fusion layer: a logistic regression over the three layer scores.

Run from project root:  python scripts/11_train_fusion.py

Inputs are the per-row layer 1 / layer 2 scores generated by the feature
build step, plus an OUT-OF-FOLD layer 3 score.

Why out-of-fold for layer 3: the sender lookup table is built from the same
custom dataset these rows come from, so an in-fold lookup would be correct on
every single row. A model trained on that learns "just copy layer 3" and then
falls apart on the ~71% of real senders that are not in the table. Building
the sender table from the training fold only means held-out rows get an
honest "unknown" whenever their sender was not seen, which is what happens at
inference time.

Missing signals (no URL in the message, sender not in the table, text empty
after cleaning) are handled with mean-imputation plus an explicit
"is present" indicator per layer, so the model can learn how much to trust a
score AND how to behave when it is absent.
"""
import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

FEATURES_CSV = PROJECT_ROOT / "data" / "processed" / "fusion_features.csv"
OUT_MODEL = PROJECT_ROOT / "saved_models" / "fusion_lr.pkl"

NEUTRAL = 0.5   # what an absent score is imputed to
N_FOLDS = 5
SEED = 42

# Deliberately NO "l2_present". In the custom dataset every phishing row
# carries a URL and no legit-without-URL row is phishing, so "has a link" is a
# perfect one-way rule there and the model latches onto it (coefficient +4.1,
# its largest). That rule is an artefact of how the dataset was collected, not
# a property of smishing - real smishing uses callback numbers and reply-bait
# with no link, and real bank/delivery SMS carry links constantly. Excluding
# it costs ~7pp of headline accuracy and buys a model that does not treat
# "no link" as proof of safety.
# Layer 3 is encoded as TWO directional indicators rather than
# (score, present). With a single "present" flag the model learned
# "layer 3 matched -> legitimate", because out-of-fold layer 3 yields 194
# legit matches and ZERO phishing ones: a phishing sender is single-use, so
# it is never in the training fold when its own row is being scored. At
# inference the full table DOES match phishing senders, and they inherited
# that exonerating weight - a sender listed as phishing came out at -1.45,
# lowering the risk. Splitting the two directions stops them sharing a
# coefficient. l3_known_phish is all-zero in training, so the model assigns
# it no evidence instead of the wrong sign; the data honestly cannot say how
# much a known-bad sender is worth, and claiming otherwise would be invented.
FEATURE_NAMES = [
    "l1_score", "l1_present",
    "l2_score",
    "l3_known_legit", "l3_known_phish",
]


def build_matrix(df: pd.DataFrame) -> np.ndarray:
    """Turn the three (possibly missing) scores into the design matrix."""
    l3 = df["l3_score"]
    columns = {
        "l1_score": df["l1_score"].fillna(NEUTRAL).astype(float).values,
        "l1_present": df["l1_score"].notna().astype(float).values,
        "l2_score": df["l2_score"].fillna(NEUTRAL).astype(float).values,
        "l2_present": df["l2_score"].notna().astype(float).values,
        "l3_known_legit": (l3 == 0.0).astype(float).values,
        "l3_known_phish": (l3 == 1.0).astype(float).values,
    }
    return np.column_stack([columns[name] for name in FEATURE_NAMES])


def out_of_fold_l3(df: pd.DataFrame, folds) -> np.ndarray:
    """
    Layer 3 score computed without letting a row see its own sender.

    For each fold the sender->label table is rebuilt from the training rows
    only; test rows whose sender does not appear there get NaN ("unknown"),
    exactly as an unseen sender would at inference time.
    """
    l3 = np.full(len(df), np.nan)
    senders = df["sender_id"].str.strip().str.upper().values
    labels = df["label"].values

    for train_idx, test_idx in folds:
        table = {}
        conflicting = set()
        for i in train_idx:
            s, lab = senders[i], labels[i]
            if s in table and table[s] != lab:
                conflicting.add(s)
            table[s] = lab
        for s in conflicting:
            table.pop(s, None)

        for i in test_idx:
            lab = table.get(senders[i])
            if lab is not None:
                l3[i] = 1.0 if lab == "phishing" else 0.0

    return l3


def main():
    if not FEATURES_CSV.exists():
        sys.exit(f"missing {FEATURES_CSV} - run the feature build step first")

    df = pd.read_csv(FEATURES_CSV)
    y = df["y"].values

    skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)
    folds = list(skf.split(df, y))

    df["l3_score"] = out_of_fold_l3(df, folds)

    X = build_matrix(df)

    print(f"rows: {len(df)}   phishing: {y.sum()}   legit: {(1-y).sum()}")
    print("signal availability:")
    for layer in ("l1", "l2", "l3"):
        n = df[f"{layer}_score"].notna().sum()
        print(f"  {layer}: {n}/{len(df)} present ({n/len(df):.0%})")

    # --- Honest evaluation: same folds used to build the out-of-fold layer 3 ---
    print(f"\n{N_FOLDS}-fold cross-validation (out-of-fold layer 3):")
    oof_pred = np.zeros(len(df))
    oof_prob = np.zeros(len(df))
    for train_idx, test_idx in folds:
        clf = LogisticRegression(max_iter=1000, class_weight="balanced", random_state=SEED)
        clf.fit(X[train_idx], y[train_idx])
        oof_pred[test_idx] = clf.predict(X[test_idx])
        oof_prob[test_idx] = clf.predict_proba(X[test_idx])[:, 1]

    print(f"  Accuracy : {accuracy_score(y, oof_pred):.4f}")
    print(f"  Precision: {precision_score(y, oof_pred, zero_division=0):.4f}")
    print(f"  Recall   : {recall_score(y, oof_pred, zero_division=0):.4f}")
    print(f"  F1       : {f1_score(y, oof_pred, zero_division=0):.4f}")
    tn, fp, fn, tp = confusion_matrix(y, oof_pred).ravel()
    print(f"  Confusion: TN={tn}  FP={fp}  FN={fn}  TP={tp}")

    # --- Per-layer solo baselines, for comparison in the report ---
    print("\nsingle-layer baselines (threshold 0.5, rows where that layer fired):")
    for layer, name in (("l1", "text"), ("l2", "URL"), ("l3", "sender")):
        m = df[f"{layer}_score"].notna().values
        if m.sum():
            acc = ((df[f"{layer}_score"].values[m] >= 0.5).astype(int) == y[m]).mean()
            print(f"  layer {layer[-1]} ({name}): {acc:.4f} on {m.sum()} rows")

    # --- Final model on all rows ---
    model = LogisticRegression(max_iter=1000, class_weight="balanced", random_state=SEED)
    model.fit(X, y)

    print("\nlearned coefficients:")
    for name, coef in zip(FEATURE_NAMES, model.coef_[0]):
        print(f"  {name:12} {coef:+.4f}")
    print(f"  {'intercept':12} {model.intercept_[0]:+.4f}")

    OUT_MODEL.parent.mkdir(exist_ok=True)
    joblib.dump({"model": model, "feature_names": FEATURE_NAMES, "neutral": NEUTRAL}, OUT_MODEL)
    print(f"\nSaved fusion model -> {OUT_MODEL}")


if __name__ == "__main__":
    main()
